sudo: required

services:
  - docker

language: node_js

node_js:
  - 7

notifications:
  email: false

env:
  global:
    - HE_VERSION=0.12.5

branches:
  only:
    - master

after_success:
  - docker build -t stono/hawkeye .
  - docker login -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD"
  - docker tag stono/hawkeye:latest stono/hawkeye:$HE_VERSION
  - docker push stono/hawkeye:latest
  - docker push stono/hawkeye:$HE_VERSION
