sudo: required

services:
  - docker

language: node_js

node_js:
  - 6
  - 7

notifications:
  email: false

branches:
  only:
    - master

before_install:
  - docker build -t stono/hawkeye .

after_success:
  - if [ "$TRAVIS_BRANCH" == "master" ]; then
    docker login -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD";
    docker push stono/hawkeye;
    fi
