sudo: required
services:
- docker
language: node_js
node_js:
- 10
notifications:
  email: false
script:
- npm test
deploy:
- provider: script
  script: bash scripts/deploy.sh
  on:
    tags: true
    all_branches: true
    condition: "$TRAVIS_TAG =~ ^v[0-9]+\\.[0-9]+\\.[0-9]+"
- provider: npm
  email: felix.hammerl@gmail.com
  api_key:
    secure: Ur0dXakenL8m5SDFMrp57yEUNtUqqGILF/K/TqZonbosU10hp0+HYLVPA0Gd0aSGPk/pOr4jbd8tR3gY7Tx9zdoGnQfUgTcmxJnhV2rUQhxbpk9AePhPXApWxwX4RQk0oxUwMt6IphG28YiZNK9pSifoO+Jk4MaIau5cSalgAWk6Ifkg6c0Cai92fU0R0tYHLOLPkMYVz/DCBcToCTM4CXGlQWwT48WmuyMxeoOreqyjHGEWZOfuYNEC/CRx7S9SEQCR/nyhperTftHDJdEeTsEhZi017vzbBTCqSxaABx2tj74VtTE1VevDPJlcC0pQUv3TH+xSznBY3IH75KjrxXrw48BlT1avOYflEdINvcKG5mKSIq5hFZHteETygH7kweTbsxJMclM9UUc2j7ADczSeIUa3Z/t9e5lklbP6cfJqypMlPpDuhll3K++4QypIHyZd2B2FppkHZ9fbAaaaekhGEExiQSdvDV6Auxs3WrVSUeveynsB7xdOZ67sUhT+2hTBKE8N/ojg2W5JYf1VMubkZ8F1yyCd4ckXXM3aOVj4VFVgqxYgTmxSNU4bDuLKTxg6b2XIyYhhO7KFsLkvmsqK1pKNTQ9ngTY0LCb0Wv64coW2i1JmtzGJrieuoZKhSXvGdp1PsAeVDGgvk7LtRehlqzGRzIRueRwngSIGjWQ=
  on:
    tags: true
    all_branches: true
    condition: "$TRAVIS_TAG =~ ^v[0-9]+\\.[0-9]+\\.[0-9]+"
