version: '2'

services:
  shell:
    image: stono/hawkeye
    build: .
    entrypoint: /bin/bash
    volumes:
      - ./lib:/hawkeye/lib
      - ./bin:/hawkeye/bin
      - ./test/samples/nodejs:/target/nodejs
      - ./test/samples/ruby:/target/ruby
      - ./test/samples/maven:/target/maven
